version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
<<<<<<< before updating
      interval: "weekly"
    cooldown:
      default-days: 7
=======
      interval: "monthly"
>>>>>>> after updating
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
